version: '3.8'

services:
  api_gateway:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - auth
      - emission
      - analytics
      - org
      - ingestion
      - reporting
      - billing
    networks:
      - esg_network

networks:
  esg_network:
    external: true
